### ISSUE TITLE
installer.sh 

### ISSUE THREAD

**Issue by Ibouro** [PeterMosmans/gitlab-demolab#1]
ibrahima@devsecops-tools:~/gitlab-demolab$ ./installer.sh 
Found existing .env file
Starting GitLab
./installer.sh: line 96: : command not found
Waiting on GitLab to initialize ... 

i have this error when i execute installer.sh

**Comment by Ibouro** [comment]
it still doesn't work, I think there's an error on line 96, otherwise I have docker-compose installed 
if i run ./installer.sh
i have this message i am on ubuntu 22.04

./installer.sh: ligne 96:  : commande introuvable
Waiting on GitLab to initialize ...

**Comment by PeterMosmans** [comment]
@Ibouro : Could you please  let me know the output of the following commands?
```
which docker-compose
which docker
docker version
docker-compose version
```

This will hopefully assist in troubleshooting this issue. Thanks!

**Comment by Ibouro** [comment]
thank you, it was docker-compose that wasn't installed.
what's the password

**Comment by PeterMosmans** [comment]
All instructions can be found in README.md - if anything's not clear, feel free to open a pull request to improve it: That would be much appreciated.
The default passwords can be found in https://github.com/PeterMosmans/gitlab-demolab/blob/main/env-example and will be shown when running `installer.sh` for the first time in the console.

**Comment by Ibouro** [comment]
thank you for taking your time, it's clear
