### ISSUE TITLE
zap module

### ISSUE THREAD

**Issue by Ibouro** [PeterMosmans/gitlab-demolab#2]
Hi
hope you are well, i have when i push zap pipeline 

![ZAP](https://github.com/PeterMosmans/gitlab-demolab/assets/93995085/34776cea-1996-4c33-a44f-e28525897356)

WARNING: Failed to pull image with policy "if-not-present": Error response from daemon: pull access denied for owasp/zap2docker-bare, repository does not exist or may require 'docker login': denied: requested access to the resource is denied (manager.go:250:1s)
ERROR: Job failed: failed to pull image "owasp/zap2docker-bare:2.14.0" with specified policies [if-not-present]: Error response from daemon: pull access denied for owasp/zap2docker-bare, repository does not exist or may require 'docker login': denied: requested access to the resource is denied (manager.go:250:1s)

**Comment by PeterMosmans** [comment]
Hey @ibouro, thanks for your comment. The repository of ZAP changed, I'll update the defaults with the current, correct version.

**Comment by PeterMosmans** [comment]
Hi @Ibouro - see https://github.com/PeterMosmans/gitlab-demolab/commit/b1f90ee318246169cb254683c965bca59e4605d8
The repo has changed to zaproxy/zaproxy-bare
Thanks for raising this issue!
